# generated by scripts/tool_serving_index.py; python3 scripts/tool_serving_index.py sync — do not edit by hand
"""Generated skill-to-tool and server tool-name indexes."""

from __future__ import annotations


SLUG_MCP_TOOLS: dict[str, tuple[str, ...]] = {
    'auto-fix': ('close_slice', 'get_handoff_state', 'integrity_check', 'record_event', 'review_findings', 'set_handoff_state'),
    'branch-lifecycle': ('close_slice', 'get_handoff_state', 'integrity_check', 'load_session', 'manage_worktree_lane', 'record_event', 'render_handoff', 'set_handoff_state', 'switch_task'),
    'branch-review': ('get_review_findings_summary', 'get_verified_tests', 'integrity_check', 'load_session', 'reconcile_review_findings', 'record_event', 'review_findings', 'review_runs', 'search_handoff', 'set_handoff_state'),
    'commit2git': (),
    'daemon-lifecycle': ('manage_orchestrator', 'manage_worker'),
    'document-sync': ('record_event', 'render_handoff', 'review_findings'),
    'handoff-lifecycle': ('close_slice', 'compaction', 'continuation', 'export_handoff_state', 'find_related_prior_work', 'get_handoff_state', 'import_handoff_state', 'list_handoff_rows', 'load_session', 'next_actions', 'record_event', 'render_handoff', 'semantic_reinjection_packet', 'set_handoff_state', 'switch_task', 'validate'),
    'incremental-implementation': ('find_related_prior_work', 'plan_cursor', 'record_event', 'search_handoff'),
    'investigate': ('find_related_prior_work', 'get_handoff_state', 'record_event', 'render_handoff', 'review_findings', 'search_handoff', 'set_handoff_state'),
    'offload': ('await_offload_pass', 'continuation', 'dispatch_lane_work', 'get_handoff_state', 'list_available_backends', 'load_session', 'manage_worktree_lane', 'materialize_offload_lane_manifest', 'offload_preflight', 'run_offload_pass', 'semantic_reinjection_packet', 'turn_metrics'),
    'plan-draft': ('review_findings', 'review_runs'),
    'planning-review': ('record_event', 'render_handoff', 'review_findings', 'review_runs', 'search_handoff', 'set_handoff_state'),
    'refactor': ('get_handoff_state', 'record_event', 'review_findings'),
    'rescue-lane': ('get_lane_activity', 'lane_communication', 'record_event', 'worker_reports'),
    'review': (),
    'review-parallel': ('get_handoff_state', 'get_latest_slice_review_packet', 'list_available_backends', 'materialize_offload_lane_manifest', 'reconcile_review_findings', 'record_event', 'review_findings', 'review_runs', 'run_structured_turn', 'search_handoff', 'semantic_reinjection_packet', 'set_handoff_state'),
    'scope': ('record_event',),
    'security-audit': ('record_event', 'review_findings', 'review_runs'),
    'spec': (),
    'subfeature-committer': (),
    'tdd': ('find_related_prior_work', 'record_event', 'search_handoff'),
    'ux-map': ('record_event', 'review_findings'),
    'wb-tombstone': (),
    'workbay': (),
    'worktree-orchestrator': ('dispatch_lane_work', 'get_lane_activity', 'lane_communication', 'manage_worktree_lane', 'plan_cursor', 'worker_reports'),
    'worktree-worker': ('get_lane_activity', 'lane_communication', 'record_event', 'review_findings', 'worker_reports'),
}

HANDOFF_TOOL_NAMES: frozenset[str] = frozenset(
    {
        'activate_tool_domain',
        'archive',
        'artifacts',
        'audit_decision_ids',
        'close_slice',
        'collect_stale_nonscratch_open_findings',
        'compaction',
        'continuation',
        'export_handoff_state',
        'find_related_prior_work',
        'get_handoff_state',
        'get_verified_tests',
        'import_handoff_state',
        'integrity_check',
        'list_handoff_rows',
        'list_tool_domains',
        'load_session',
        'next_actions',
        'reconcile_reviewer_scratch_findings_gc',
        'record_event',
        'render_handoff',
        'review_findings',
        'review_runs',
        'search_handoff',
        'semantic_reinjection_packet',
        'set_handoff_state',
        'terminal_guard_telemetry',
        'touched_files',
        'validate',
    }
)

ORCHESTRATOR_TOOL_NAMES: frozenset[str] = frozenset(
    {
        'activate_tool_domain',
        'await_offload_pass',
        'await_offload_passes',
        'dispatch_lane_work',
        'dispatch_wave',
        'get_lane_activity',
        'get_latest_slice_review_packet',
        'get_metrics_summary',
        'get_review_findings_summary',
        'lane_communication',
        'list_available_backends',
        'list_tool_domains',
        'manage_orchestrator',
        'manage_worker',
        'manage_worktree_lane',
        'materialize_offload_lane_manifest',
        'offload_preflight',
        'plan_cursor',
        'reconcile_review_findings',
        'run_offload_pass',
        'run_structured_turn',
        'switch_task',
        'turn_metrics',
        'worker_reports',
    }
)

# Verified intersection of the two server tool-name sets.
SHARED_TOOL_NAMES: frozenset[str] = frozenset(
    {
        'activate_tool_domain',
        'list_tool_domains',
    }
)
