#!/usr/bin/env python3
"""Generate the protocol's tool-serving index.

ToolEntry names must be string literals. The AST reader accepts only
``ToolEntry("name", ...)`` and rejects derived or keyword-named entries so
regeneration fails at the offending source location instead of silently drifting.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_RELPATH = "packages/workbay-system/workbay_system/payload/skills"
HANDOFF_API_RELPATH = "packages/mcp-workbay-handoff/src/workbay_handoff_mcp/api.py"
ORCHESTRATOR_API_RELPATH = (
    "packages/mcp-workbay-orchestrator/src/workbay_orchestrator_mcp/api.py"
)
OUTPUT_RELPATH = (
    "packages/workbay-protocol/src/workbay_protocol/tool_serving_index.py"
)
SENTINEL = (
    "# generated by scripts/tool_serving_index.py; "
    "python3 scripts/tool_serving_index.py sync — do not edit by hand"
)
EXPECTED_SHARED_TOOL_NAMES = {"activate_tool_domain", "list_tool_domains"}
SKILL_MANIFEST_SHAPE = (
    "expected valid YAML containing a top-level mapping with an optional "
    "mcp_tools list of unique non-empty strings"
)
TOOL_ENTRY_SHAPE = (
    'expected ToolEntry("<literal>", ...) with a positional string literal'
)


def _one_line(error: BaseException) -> str:
    return " ".join(str(error).splitlines())


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise SystemExit(f"cannot read {path}: {_one_line(error)}") from error


def _write_text(path: Path, contents: str) -> None:
    path.write_text(contents, encoding="utf-8")


def _tool_entry_names(api_path: Path) -> set[str]:
    tree = ast.parse(_read_text(api_path))
    names: set[str] = set()
    for node in tree.body:
        is_assignment_alias = isinstance(node, ast.Assign) and (
            (isinstance(node.value, ast.Name) and node.value.id == "ToolEntry")
            or (isinstance(node.value, ast.Attribute) and node.value.attr == "ToolEntry")
        )
        is_import_alias = isinstance(node, ast.Import) and any(
            alias.asname and alias.name.rsplit(".", 1)[-1] == "ToolEntry"
            for alias in node.names
        )
        is_from_import_alias = isinstance(node, ast.ImportFrom) and any(
            alias.asname and alias.name == "ToolEntry" for alias in node.names
        )
        if is_assignment_alias or is_import_alias or is_from_import_alias:
            raise SystemExit(
                f"aliased ToolEntry at {api_path}:{node.lineno}; {TOOL_ENTRY_SHAPE}"
            )
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        is_entry = (isinstance(func, ast.Name) and func.id == "ToolEntry") or (
            isinstance(func, ast.Attribute) and func.attr == "ToolEntry"
        )
        if not is_entry:
            continue
        literal_name = (
            node.args
            and isinstance(node.args[0], ast.Constant)
            and isinstance(node.args[0].value, str)
        )
        if any(keyword.arg == "name" for keyword in node.keywords) or not literal_name:
            raise SystemExit(
                f"invalid ToolEntry call at {api_path}:{node.lineno}; {TOOL_ENTRY_SHAPE}"
            )
        names.add(node.args[0].value)
    return names


def _slug_mcp_tools(repo_root: Path) -> dict[str, tuple[str, ...]]:
    skills_root = repo_root / SKILLS_RELPATH
    result: dict[str, tuple[str, ...]] = {}
    for manifest_path in sorted(skills_root.glob("*/skill.yaml")):
        try:
            manifest = yaml.safe_load(_read_text(manifest_path))
        except yaml.YAMLError as error:
            raise SystemExit(
                f"invalid YAML at {manifest_path}: {_one_line(error)}; "
                f"{SKILL_MANIFEST_SHAPE}"
            ) from error
        if not isinstance(manifest, dict):
            raise SystemExit(
                f"skill manifest is not a mapping: {manifest_path}; "
                f"{SKILL_MANIFEST_SHAPE}"
            )
        raw_tools = manifest.get("mcp_tools", [])
        if not isinstance(raw_tools, list) or not all(
            isinstance(tool, str) and tool for tool in raw_tools
        ):
            raise SystemExit(
                f"invalid mcp_tools list: {manifest_path}; {SKILL_MANIFEST_SHAPE}"
            )
        if len(raw_tools) != len(set(raw_tools)):
            raise SystemExit(
                f"duplicate mcp_tools entry: {manifest_path}; {SKILL_MANIFEST_SHAPE}"
            )
        result[manifest_path.parent.name] = tuple(sorted(raw_tools))
    if not result:
        raise SystemExit(
            f"no skill manifests under {skills_root}; expected at least one "
            "<slug>/skill.yaml matching the accepted skill manifest shape"
        )
    return result


def _skill_tool_lookup(
    slug_tools: dict[str, tuple[str, ...]], skill_dir: Path
) -> tuple[str, ...]:
    try:
        return slug_tools[skill_dir.name]
    except KeyError as error:
        raise SystemExit(
            f"no skill manifest for {skill_dir}; expected {skill_dir / 'skill.yaml'}"
        ) from error


def _render_tuple(values: tuple[str, ...]) -> str:
    if not values:
        return "()"
    if len(values) == 1:
        return f"({values[0]!r},)"
    return "(" + ", ".join(repr(value) for value in values) + ")"


def _render_frozenset(name: str, values: set[str]) -> list[str]:
    lines = [f"{name}: frozenset[str] = frozenset(", "    {"]
    lines.extend(f"        {value!r}," for value in sorted(values))
    lines.extend(["    }", ")", ""])
    return lines


def render(repo_root: Path) -> str:
    slug_tools = _slug_mcp_tools(repo_root)
    skill_dirs = sorted(
        path for path in (repo_root / SKILLS_RELPATH).iterdir() if path.is_dir()
    )
    handoff_names = _tool_entry_names(repo_root / HANDOFF_API_RELPATH)
    orchestrator_names = _tool_entry_names(repo_root / ORCHESTRATOR_API_RELPATH)
    overlap = handoff_names & orchestrator_names
    if overlap != EXPECTED_SHARED_TOOL_NAMES:
        raise SystemExit(
            "unexpected tool names served by both servers: "
            f"expected {sorted(EXPECTED_SHARED_TOOL_NAMES)}, got {sorted(overlap)}; "
            "update order: edit the api.py files; update "
            "EXPECTED_SHARED_TOOL_NAMES; run "
            "`python3 scripts/tool_serving_index.py sync`; run "
            "packages/workbay-protocol/tests/test_tool_serving_index.py and "
            "packages/workbay-system/tests/test_skill_mcp_tools_match_body_calls.py"
        )

    lines = [
        SENTINEL,
        '"""Generated skill-to-tool and server tool-name indexes."""',
        "",
        "from __future__ import annotations",
        "",
        "",
        "SLUG_MCP_TOOLS: dict[str, tuple[str, ...]] = {",
    ]
    lines.extend(
        f"    {skill_dir.name!r}: "
        f"{_render_tuple(_skill_tool_lookup(slug_tools, skill_dir))},"
        for skill_dir in skill_dirs
    )
    lines.extend(["}", ""])
    lines.extend(_render_frozenset("HANDOFF_TOOL_NAMES", handoff_names))
    lines.extend(_render_frozenset("ORCHESTRATOR_TOOL_NAMES", orchestrator_names))
    lines.append("# Verified intersection of the two server tool-name sets.")
    lines.extend(_render_frozenset("SHARED_TOOL_NAMES", overlap))
    return "\n".join(lines)


def sync(repo_root: Path) -> bool:
    output_path = repo_root / OUTPUT_RELPATH
    expected = render(repo_root)
    if output_path.is_file() and _read_text(output_path) == expected:
        return False
    try:
        _write_text(output_path, expected)
    except OSError as error:
        raise SystemExit(f"cannot write {output_path}: {_one_line(error)}") from error
    return True


def check(repo_root: Path) -> bool:
    output_path = repo_root / OUTPUT_RELPATH
    expected = render(repo_root)
    if not output_path.is_file():
        print(
            f"ABSENT {OUTPUT_RELPATH}; run `python3 scripts/tool_serving_index.py sync`",
            file=sys.stderr,
        )
        return False
    actual = _read_text(output_path)
    valid = True
    if not actual.startswith(SENTINEL + "\n"):
        print(
            f"CORRUPT {OUTPUT_RELPATH}; run `python3 scripts/tool_serving_index.py sync`",
            file=sys.stderr,
        )
        valid = False
    if actual != expected:
        print(
            f"DRIFT {OUTPUT_RELPATH}; run `python3 scripts/tool_serving_index.py sync`",
            file=sys.stderr,
        )
        valid = False
    if not valid:
        return False
    print(f"ok: {OUTPUT_RELPATH} is current")
    return True


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the protocol's tool-serving index from string-literal "
            "ToolEntry names."
        )
    )
    parser.add_argument("command", choices=("sync", "check"))
    parser.add_argument("--repo-root", default=str(REPO_ROOT))
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    repo_root = Path(args.repo_root).resolve()
    if args.command == "sync":
        changed = sync(repo_root)
        print(
            "tool-serving-index-sync: index rewritten"
            if changed
            else "tool-serving-index-sync: already in sync"
        )
        return 0
    return 0 if check(repo_root) else 1


if __name__ == "__main__":
    raise SystemExit(main())
